name: 'Buildah Build'
description: 'Build a container image, with or without a Containerfile'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'The name (reference) of the image to build'
    required: false
  tags:
    description: 'The tags of the image to build. For multiple tags, seperate by whitespace. For example, "latest v1".'
    required: false
    default: latest
  labels:
    description: 'The labels of the image to build. Seperate by newline. For example, "io.containers.capabilities=sys_admin,mknod".'
    required: false
  base-image:
    description: 'The base image to use to create a new container image'
    required: false
  containerfiles:
    description: 'List of Containerfile paths (eg: ./Containerfile)'
    required: false
  dockerfiles:
    description: 'Alias for "containerfiles". "containerfiles" takes precedence if both are set.'
    required: false
  context:
    description: 'Path of the directory to use as context (default: .)'
    required: false
    default: '.'
  content:
    description: 'List of files/directories to copy inside the base image'
    required: false
  entrypoint:
    description: 'The entry point to set for containers based on image'
    required: false
  layers:
    description: 'Set to true to cache intermediate layers during build process'
    required: false
  port:
    description: 'The port to expose when running containers based on image'
    required: false
  workdir:
    description: 'The working directory to use within the container'
    required: false
  envs:
    description: 'List of environment variables to be set when running containers based on image'
    required: false
  build-args:
    description: 'List of --build-args to pass to buildah'
    required: false
  oci:
    description: 'Set to true to build using the OCI image format instead of the Docker image format'
    default: 'false'
    required: false
  arch:
    description:
      'Label the image with this ARCH, instead of defaulting to the host architecture'
    required: false
  archs:
    description: |
      'Same as input 'arch', use this for multiple architectures.
      Seperate them by a comma'
    required: false
  platform:
    description: |
      Label the image with this PLATFORM, instead of defaulting to the host platform.
      Only supported for containerfile builds.
    required: false
  platforms:
    description: |
      'Same as input 'platform', use this for multiple platforms.
      Seperate them by a comma'
    required: false
  extra-args:
    description: |
      Extra args to be passed to buildah bud.
      Separate arguments by newline. Do not use quotes - @actions/exec will do the quoting for you.
    required: false
outputs:
  image:
    description: 'Name of the image built'
  tags:
    description: 'List of the tags that were created, separated by spaces'
  image-with-tag:
    description: 'Name of the image tagged with the first tag present'
runs:
  using: 'node12'
  main: 'dist/index.js'
