name: 'Buildah Build'
description: 'Build a container image, with or without a Dockerfile'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'The name (reference) of the image to build'
    required: true
  tag:
    description: 'The tag of the image to build'
    required: false
    default: latest
  base-image:
    description: 'The base image to use to create a new container image'
    required: false
  dockerfiles:
    description: 'List of Dockerfile paths (eg: ./Dockerfile)'
    required: false
  context:
    description: 'Path of the directory to use as context (default: .)'
    required: false
    default: '.'
  content:
    description: 'List of files/directories to copy inside the base image'
    required: false
  entrypoint:
    description: 'The entry point to set for containers based on image'
    required: false
  port:
    description: 'The port to expose when running containers based on image'
    required: false
  workdir:
    description: 'The working directory to use within the container'
    required: false
  envs:
    description: 'List of environment variables to be set when running containers based on image'
    required: false
  build-args:
    description: 'List of --build-args to pass to buildah.'
    required: false
  oci:
    description: 'Set to true to build using the OCI image format instead of the Docker image format.'
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
